name = "Touchofspice"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://www.touchofspice.co.nz/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "James Morgan"
  homepage = "https://nz.linkedin.com/in/james-morgan-nz"